version: "3.1"
services:
  cassandra:
    image: "cassandra:3.11.2"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    network_mode: 'host'